version: "3.7"

services:
  db:
    image: postgres:13.2
    init: true
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - "db:/var/lib/postgresql/data:delegated"
    environment:
      POSTGRES_USER: phonebook
      POSTGRES_PASSWORD: phonebook

volumes:
  db:
